Repository rabbitmq/rabbitmq-dotnet-client, pull requests merged in 2020-04, with the labels that each got.

#801 Serialization optimizations
  projects/RabbitMQ.Client/util/NetworkOrderDeserializer.cs
  projects/RabbitMQ.Client/util/NetworkOrderSerializer.cs
Labels: enhancement

#808 Run tests on multiple frameworks
  .travis.yml
  projects/Unit/Fixtures.cs
  projects/Unit/TestBlockingCell.cs
  projects/Unit/TestSharedQueue.cs
  projects/Unit/Unit.csproj
  run-test.sh
Labels: effort-low

#809 Enable deterministic builds
  RabbitMQDotNetClient.sln
  projects/Directory.Build.targets
  projects/RabbitMQ.Client/RabbitMQ.Client.csproj
Labels: effort-low, enhancement

#818 Fall back to rabbitmqctl (or rabbitmqctl.bat) if RABBITMQ_RABBITMQCTL_PATH or umbrella path are not available
  projects/Unit/Fixtures.cs
Labels: effort-tiny, enhancement
