Repository rabbitmq/rabbitmq-dotnet-client, pull requests merged in 2020-03, with the labels that each got.

#746 Always sign builds
  .gitignore
  RabbitMQDotNetClient.sln
  appveyor.yml
  projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj
  projects/client/RabbitMQ.Client/src/client/properties/AssemblyInfo.cs
  projects/client/Unit/Unit.csproj
  projects/client/Unit/src/unit/APIApproval.Approve.approved.txt
  projects/client/rabbit.snk
  rabbit.snk.enc
  rabbit.snk.prbuilds
Labels: effort-low, enhancement

#748 Remove traces of paket
  .gitignore
  .paket/paket.bootstrapper.exe
  paket.dependencies
  paket.lock
Labels: effort-tiny

#749 Merge pull request #748 from rabbitmq/rabbitmq-dotnet-client-747
  .gitignore
  .paket/paket.bootstrapper.exe
  paket.dependencies
  paket.lock
Labels: effort-tiny, enhancement

#750 Add Travis CI build
  .travis.yml
  run-test.sh
Labels: effort-medium, enhancement

#751 Merge pull request #750 from rabbitmq/lrb-travis-ci
  .travis.yml
  run-test.sh
Labels: effort-low, enhancement

#757 Catch ObjectDisposedException case
  projects/client/RabbitMQ.Client/src/client/impl/Connection.cs
Labels: effort-tiny, enhancement

#760 Yield to prevent deadlocks
  projects/client/RabbitMQ.Client/src/client/impl/Work.cs
Labels: effort-tiny, enhancement, next-gen-todo

#759 Expose nowait version of BasicCancel
  projects/client/RabbitMQ.Client/src/client/api/IModel.cs
  projects/client/RabbitMQ.Client/src/client/impl/AutorecoveringModel.cs
  projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs
  projects/client/Unit/src/unit/APIApproval.Approve.approved.txt
  projects/client/Unit/src/unit/TestAsyncConsumer.cs
Labels: effort-tiny, enhancement

#763 Public api cleanup round 2
  projects/client/Apigen/src/apigen/Apigen.cs
  projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs
  projects/client/RabbitMQ.Client/src/client/api/ConnectionFactoryBase.cs
  projects/client/RabbitMQ.Client/src/client/api/ExternalMechanism.cs
  projects/client/RabbitMQ.Client/src/client/api/ExternalMechanismFactory.cs
  projects/client/RabbitMQ.Client/src/client/api/IAuthMechanism.cs
  projects/client/RabbitMQ.Client/src/client/api/IAuthMechanismFactory.cs
  projects/client/RabbitMQ.Client/src/client/api/IConnection.cs
  projects/client/RabbitMQ.Client/src/client/api/IConnectionFactory.cs
  projects/client/RabbitMQ.Client/src/client/api/INetworkConnection.cs
  projects/client/RabbitMQ.Client/src/client/api/PlainMechanism.cs
  projects/client/RabbitMQ.Client/src/client/api/PlainMechanismFactory.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/ChannelErrorException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/HardProtocolException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/MalformedFrameException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/ProtocolException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/ProtocolViolationException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/SoftProtocolException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/SyntaxErrorException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/TopologyRecoveryException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/UnexpectedFrameException.cs
  projects/client/RabbitMQ.Client/src/client/exceptions/UnknownClassOrMethodException.cs
  projects/client/RabbitMQ.Client/src/client/impl/AmqpVersion.cs
  projects/client/RabbitMQ.Client/src/client/impl/AsyncConsumerWorkService.cs
  projects/client/RabbitMQ.Client/src/client/impl/AutorecoveringConnection.cs
  projects/client/RabbitMQ.Client/src/client/impl/BinaryTableValue.cs
  projects/client/RabbitMQ.Client/src/client/impl/Command.cs
  projects/client/RabbitMQ.Client/src/client/impl/CommandAssembler.cs
  projects/client/RabbitMQ.Client/src/client/impl/Connection.cs
  projects/client/RabbitMQ.Client/src/client/impl/ConsumerWorkService.cs
  projects/client/RabbitMQ.Client/src/client/impl/ContentHeaderPropertyReader.cs
  projects/client/RabbitMQ.Client/src/client/impl/SslHelper.cs
  projects/client/RabbitMQ.Client/src/client/impl/TcpClientAdapter.cs
  projects/client/RabbitMQ.Client/src/client/impl/TcpClientAdapterHelper.cs
  projects/client/RabbitMQ.Client/src/client/impl/WireFormatting.cs
  projects/client/RabbitMQ.Client/src/client/logging/ESLog.cs
  projects/client/RabbitMQ.Client/src/client/logging/RabbitMqClientEventSource.cs
  projects/client/RabbitMQ.Client/src/client/logging/RabbitMqConsoleEventListener.cs
  projects/client/RabbitMQ.Client/src/client/logging/RabbitMqExceptionDetail.cs
  projects/client/Unit/src/unit/APIApproval.Approve.approved.txt
  projects/client/Unit/src/unit/TestTcpClientAdapter.cs
Labels: enhancement

#789 Use a more verbose version for pull requests
  projects/RabbitMQ.Client/RabbitMQ.Client.csproj
Labels: effort-tiny, enhancement

#792 Modify pull request package info
  projects/RabbitMQ.Client/RabbitMQ.Client.csproj
Labels: effort-tiny, enhancement

#796 Package updates
  projects/RabbitMQ.Client/RabbitMQ.Client.csproj
  projects/RabbitMQ.Client/client/impl/TcpClientAdapter.cs
  projects/Unit/Unit.csproj
Labels: enhancement

#795 Change log and basic doc updates for 6.x
  CHANGELOG.md
  README.md
  RUNNING_TESTS.md
  projects/RabbitMQ.Client/client/api/AsyncDefaultBasicConsumer.cs
  projects/RabbitMQ.Client/client/api/DefaultBasicConsumer.cs
  projects/RabbitMQ.Client/client/events/AsyncEventingBasicConsumer.cs
  projects/RabbitMQ.Client/client/events/EventingBasicConsumer.cs
Labels: doc, effort-low, enhancement

#798 Fix solution configuration
  RabbitMQDotNetClient.sln
Labels: effort-tiny
