Repository rabbitmq/rabbitmq-dotnet-client, pull requests merged in 2020-05, with the labels that each got.

#831 Introduce PublicationAddress.TryParse and switch BasicProperties.ReplyToAddress to use it
  projects/RabbitMQ.Client/client/api/IBasicProperties.cs
  projects/RabbitMQ.Client/client/api/PublicationAddress.cs
  projects/RabbitMQ.Client/client/impl/BasicProperties.cs
  projects/Unit/APIApproval.Approve.verified.txt
  projects/Unit/TestBasicProperties.cs
  projects/Unit/TestPropertiesClone.cs
  projects/Unit/TestPublicationAddress.cs
Labels: enhancement

#837 Replacing usage of ManualResetEvent with ManualResetEventSlim
  projects/RabbitMQ.Client/client/impl/Connection.cs
  projects/RabbitMQ.Client/client/impl/ModelBase.cs
  projects/Unit/Fixtures.cs
  projects/Unit/TestConnectionRecovery.cs
  projects/Unit/TestConnectionShutdown.cs
  projects/Unit/TestConsumerOperationDispatch.cs
  projects/Unit/TestEventingConsumer.cs
  projects/Unit/TestModelShutdown.cs
Labels: effort-tiny, enhancement

#824 Optimizing memory usage even further.
  projects/RabbitMQ.Client/client/api/AsyncDefaultBasicConsumer.cs
  projects/RabbitMQ.Client/client/api/IBasicPublishBatch.cs
  projects/RabbitMQ.Client/client/exceptions/UnexpectedFrameException.cs
  projects/RabbitMQ.Client/client/impl/AsyncConsumerDispatcher.cs
  projects/RabbitMQ.Client/client/impl/BasicDeliver.cs
  projects/RabbitMQ.Client/client/impl/BasicPublishBatch.cs
  projects/RabbitMQ.Client/client/impl/Command.cs
  projects/RabbitMQ.Client/client/impl/CommandAssembler.cs
  projects/RabbitMQ.Client/client/impl/ConcurrentConsumerDispatcher.cs
  projects/RabbitMQ.Client/client/impl/Frame.cs
  projects/RabbitMQ.Client/client/impl/IConsumerDispatcher.cs
  projects/RabbitMQ.Client/client/impl/ModelBase.cs
  projects/RabbitMQ.Client/client/impl/SocketFrameHandler.cs
  projects/RabbitMQ.Client/util/StreamExtensions.cs
Labels: enhancement

#835 Adding System.Threading.Channels for simplified, better performing code.
  projects/RabbitMQ.Client/RabbitMQ.Client.csproj
  projects/RabbitMQ.Client/client/events/AsyncEventingBasicConsumer.cs
  projects/RabbitMQ.Client/client/impl/AsyncConsumerWorkService.cs
  projects/RabbitMQ.Client/client/impl/AutorecoveringConnection.cs
  projects/RabbitMQ.Client/util/AsyncConcurrentQueue.cs
Labels: next-gen-todo

#854 simplify missed heartbeat recognition
  projects/RabbitMQ.Client/client/impl/Connection.cs
Labels: enhancement
